# Modeling Simple Games and Nash Equilibria
Here, we model some simple games, i.e., strategic interactions between self-interested participants, and then find their Nash Equilibrium. The Python library Nashpy is used here.

In [1]:
# First, import required modules
import numpy as np
import nashpy as nash

## 1. Computer networking game
Your computer and another computer are sending messages to the internet. They manage congesion by implementing backoff mechanism in the TCP protocol. In the backoff mechanism, the computer reduces the speed of its message transmission when it recognizes a congestion.

– If both computers implement the backoff mechanism: both get 1 ms delay 

– If one implements the backoff mechanism (correct) while the other does not (defective): the delay is 4 ms for the correct implementation and 0 ms for the defective implementation

– If both do not implement the backoff mechanism (defective): both experience a 3 ms delay

If you wanted to minimize the amount of delay that you experienced on your computer, how would you play this game? 

In [2]:
row_player_A = np.array([[1,0],[4,3]])
col_player_B = np.array([[1,4],[0,3]])
comp_net_game = nash.Game(row_player_A,col_player_B)
comp_net_game

Bi matrix game with payoff matrices:

Row player:
[[1 0]
 [4 3]]

Column player:
[[1 4]
 [0 3]]

In [3]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = comp_net_game.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))


**Nash Equilibrium Solution**: This result can be interpreted as follows. In the problem, each player has 2 strategies. Player A has strategies = (Top, Bottom). Player B has strategies = (Left, Right).

The output shows that 

Player A chooses strategy 2 i.e. ‘Bottom’ as given by ‘1’ in the second position of the array.

Player B chooses strategy 1 i.e. ‘Right’ as given by ‘1’ in the second position of the array. 

Hence, the Nash Equilibrium is (Bottom, Right), i.e., (defective, defective).

## 2. Rock, Paper, Scissors
Find the Nash Equilibrium in the traditional rock, paper, scissors game (https://en.wikipedia.org/wiki/Rock_paper_scissors).

- Each player simultaneously forms one of three shapes with an outstretched hand. 
- These shapes are "rock" (a closed fist), "paper" (a flat hand), and "scissors" (a fist with the index finger and middle finger extended, forming a V). 

- A player who decides to play rock will beat another player who has chosen scissors ("rock crushes/blunts scissors"). 
- But a play of rock will lose to one who has played paper ("paper covers rock"). 
- And a play of paper will lose to a play of scissors ("scissors cuts paper"). 
- If both players choose the same shape, the game is tied and is usually immediately replayed to break the tie.

In [4]:
row_player_A = np.array([[0,-1,1],[1,0,-1], [-1,1,0]])
col_player_B = np.array([[0,1,-1],[-1,0,1], [1,-1,0]])
ro_pa_sc_game = nash.Game(row_player_A,col_player_B)
ro_pa_sc_game

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

In [5]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = ro_pa_sc_game.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0.33333333, 0.33333333, 0.33333333]), array([0.33333333, 0.33333333, 0.33333333]))


**Nash Equilibrium Solution**: Thus, this game has only one mixed-strategy Nash Equilibrium and no pure-strategy Nash Equilibrium. And this equilibrium is not very useful practically, because (1) you have to choose any one of the three alternatives (mixed strategy cannot be used), and (2) the games are repeated.

This is a good illustration of the fact that while according to Nash's theorem, *all finite games must have at least one Nash Equilibria*, this theorem holds true only for mixed strategies and not for pure strategies!.

## 3. Movie Watching

Consider a situation where a husband and a wife want to watch something on TV; above all, they want to watch together. The wife wants to watch a live sports game while the husband wants to watch a romantic comedy. If they do this separately, then they are equally unhappy. They want to watch together, but they have conflicting preferences: thus, there is both cooperation and competition in this game.

In [6]:
row_player_A = np.array([[2,0],[0,1]])
col_player_B = np.array([[1,0],[0,2]])
movie_watch_game = nash.Game(row_player_A,col_player_B)
movie_watch_game

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [0 1]]

Column player:
[[1 0]
 [0 2]]

In [7]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = movie_watch_game.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667]))


**Nash Equilibrium Solution**: This game has two pure strategy Nash Equilibriums and one mixed strategy Nash Equilibriums.

## 4. Prisoner's Dilemma

**Problem**

Two prisoners who have partnered in a crime get caught and are arrested and imprisoned. They are being questioned in separate rooms so that they cannot communicate with each other. The prosecutors lack sufficient evidence to convict the pair for the main crime. So, the prosecutors simultaneously offer each prisoner a bargain. 

Each prisoner is given the opportunity either to: betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The offer (made separately) is:

• *Betrayal-Betrayal*: If A and B betray each other, both will serves 2 years in prison 

• *Betrayal-Sucker*: If A betrays B but B remains silent, A will be set free and B will serve 3 years in prison (and vice versa)

• *Co-operation-Cooperation*: If A and B both remain silent, both of them will only serve 1 year in prison (for a lesser crime for whcih the prosecutors have evidence)

Note: It is implied that the prisoners will have no opportunity to reward or punish their partner other than the prison sentences they get, and that their decision will not affect their reputation in the future.

In [8]:
# Create the payoff matrix
A = np.array([[2,3],[0,1]]) # A is the row player
B = np.array([[2,0],[3,1]]) # B is the column player
prisoner_dilemma_game = nash.Game(A,B)
prisoner_dilemma_game

Bi matrix game with payoff matrices:

Row player:
[[2 3]
 [0 1]]

Column player:
[[2 0]
 [3 1]]

In [9]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = prisoner_dilemma_game.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))


**Nash Equilibrium Solution**: The Nash Equilibrium is (2,2), i.e., betray each other. This is because betraying a partner offers a greater reward than cooperating. So, all purely rational self-interested prisoners would betray the other, and so the only possible outcome for two purely rational prisoners is for them to betray each other. 

The interesting part of this result is that pursuing individual rewards logically lead both of the prisoners to betray, when they would get a better reward if they both kept silent. In reality, humans display a systematic bias towards cooperative behavior in this and similar games, much more so than predicted by simple models of “rational” self-interested action.

## Infinite Prisoner's Dilemma
When the game is played multiple number of times, then there is a range of other strategic possibilities available to each player. The strategies depend on whether the game is played for a finite/infinite number of times.

For an analysis of how this could work, see https://axelrod.readthedocs.io/en/stable/reference/description.html